FROM python:3.11-slim

WORKDIR /app

# 依存関係のインストール
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# ユニット固有のソースコードをコピー
COPY . .

# Flaskアプリケーションの起動
CMD ["python", "main.py"]